## Random Number

In [1]:
import random

a = random.random()                  ## This is a random float in the range from 0 to 1
print (a)

0.770022887615071


In [2]:
import random 
a = random.uniform(1, 10)          ## This will produce a random float in this range
print (a)

4.425211925391244


In [3]:
import random 
a = random.randrange(1, 10)          ## This will pick a random integer in this range
print (a)

9


In [4]:
import random 

mylist = ("ABCDFGH")                   ## This will pick random choice from string

a = random.choice(mylist)                  
print (a)

D


In [5]:
import random
mylist = ("ABCDFGH") 
a = random.sample(mylist, 3)           ## We can pick multiple elements
print (a)

['C', 'F', 'B']


In [6]:
import random
mylist = list("ABCDFGH") 
random.shuffle(mylist)         ## This is shuffle method
print (mylist)

['A', 'G', 'D', 'C', 'B', 'F', 'H']


In [7]:
import numpy as np
a = np.random.rand(3)
print (a)

[0.22941388 0.26636236 0.46859713]


In [8]:
import numpy as np
a = np.random.rand(3, 3)
print (a)

[[0.9338776  0.3025153  0.18084195]
 [0.60960587 0.69442547 0.00193576]
 [0.16199561 0.04834287 0.1833126 ]]


## Decorator

In [10]:
def start_end_decorator(func):

    def wrapper():
        print('Start')
        func()
        print('End')
    return wrapper

def print_name():
    print('Salman')

print_name = start_end_decorator(print_name)
print_name ()            

Start
Salman
End


In [13]:
def start_end_decorator(func):

    def wrapper(*args, **kwargs):
        print('Start')
        result = func(*args, **kwargs)
        print('End')
        return result
    return wrapper

@start_end_decorator
def add5(x):
    return x + 5

result = add5(10) 
print (result)   

Start
End
15


In [14]:
import functools

def repeat(num_times):
    def decorator_repeat(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            for _ in range (num_times):
                result = func (*args, **kwargs)
            return result
        return wrapper
    return decorator_repeat

@repeat(num_times=4)
def greet(name):
    print (f'Hello {name}')                

greet('Salman')    

Hello Salman
Hello Salman
Hello Salman
Hello Salman


In [16]:
class CountCalls:
    def __init__(self, func):
        self.func = func
        self.num_calls = 0

    def __call__(self, *args, **kwargs):
        self.num_calls += 1
        print (f'This is executed {self.num_calls} times')
        return self.func(*args, **kwargs)

@CountCalls
def say_hello():
    print ('Hello') 

say_hello()               

This is executed 1 times
Hello
